package Client_GUI_Form;

import javax.swing.JFrame;

import Client_Function.C_ClientThread;
import Client_Function.C_WaitingRoom;

public class GUI_QuickMachJFrame extends javax.swing.JFrame  implements Runnable {

	JFrame prevJFrame;
	C_WaitingRoom c_WaitingRoom;
	
    public GUI_QuickMachJFrame(JFrame prevJFrame, C_WaitingRoom c_WaitingRoom) {
        initComponents();
        this.prevJFrame = prevJFrame;
		this.prevJFrame.setVisible(false);
		setLocationRelativeTo(null);
		setVisible(true);
		this.c_WaitingRoom = c_WaitingRoom;
        new Thread(this).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        waiting_jLabel = new javax.swing.JLabel();
        Back_jButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("빠른대전 임시화면");

        jLabel1.setFont(new java.awt.Font("굴림", 1, 48)); // NOI18N
        jLabel1.setText("빠른대전 임시화면");

        jLabel2.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        jLabel2.setText("매칭상대를 기다리고 있습니다");

        waiting_jLabel.setFont(new java.awt.Font("굴림", 0, 48)); // NOI18N
        waiting_jLabel.setText("");

        Back_jButton.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        Back_jButton.setText("빠른대전 취소하기");
        Back_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(waiting_jLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Back_jButton)
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(waiting_jLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(Back_jButton)
                .addGap(42, 42, 42))
        );

        pack();
    }               

    // 빼른대전 취소하기 버튼을 눌렀을 때, 대기실 화면으로 돌아간다.
    private void Back_jButtonActionPerformed(java.awt.event.ActionEvent evt) {  
    	System.out.println("빼른대전 취소하기 버튼을 눌렀을 때, 대기실 화면으로 돌아간다.");
    	c_WaitingRoom.quickMatchCancle();
    	prevJFrame.setVisible(true);
		this.dispose();
    }                                            

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_QuickMachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_QuickMachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_QuickMachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_QuickMachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
    private javax.swing.JButton Back_jButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel waiting_jLabel;
	@Override
	public void run() {
    	String waiting = "";
    	int i=0;
    	try {
    		while(true){
    			waiting+=".";
    			i++;
    			if(i==4){
    				i=0;
    				waiting = "";
    			}
    			Thread.sleep(1000);
    			waiting_jLabel.setText(waiting);
    		}
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
	}
}